# .air.toml
# Configuration for Air

# Sets the root directory of the project
root = "."

# Sets the Go build flags
build = {
  cmd = "go build -o ./bin/app",  
  bin = "./bin/app",
  ignore = ["\\.git", "assets", "tmp"],  
}

# Watcher settings
watch = {
  dir = ["."],           
  extensions = [".go"],   
}

# Run settings
run = {
  cmd = "./bin/app",    
  delay = "100ms",      
}