// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Affiliate struct {
	ID              pgtype.UUID
	Name            string
	MasterAffiliate pgtype.UUID
	Balance         float64
}

type Commission struct {
	ID          pgtype.UUID
	OrderID     pgtype.UUID
	AffiliateID pgtype.UUID
	Amount      float64
}

type Product struct {
	ID       pgtype.UUID
	Name     string
	Quantity int32
	Price    float64
}

type User struct {
	ID          pgtype.UUID
	Username    string
	Balance     float64
	AffiliateID pgtype.UUID
}
